<?php

namespace App\Observers;

use App\Models\Category;
use App\Support\WebpImage;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * Converts admin-uploaded category banner/thumbnail images to WebP.
 *
 * banner_desktop and thumbnail are simple "convert and cap the width"
 * conversions, same idea as ProductImageObserver but without the multi-size
 * srcset ladder -- these are single-purpose hero/thumbnail images, not a
 * gallery. banner_mobile is more involved: if the admin uploads one
 * explicitly it's respected as-is (converted, not cropped), but if they
 * don't, one is auto-generated by cropping banner_desktop to exactly
 * 750x500 (3:2) with Intervention's cover(), which scales-to-fill and crops
 * the excess -- centered -- so the mobile banner is never distorted or
 * letterboxed. That auto-generated banner is regenerated whenever
 * banner_desktop changes, but an admin's own explicit mobile upload is
 * never overwritten by a later desktop change.
 */
class CategoryObserver
{
    private const DESKTOP_MAX_WIDTH = 1920;

    private const MOBILE_MAX_WIDTH = 900;

    private const MOBILE_AUTO_WIDTH = 750;

    private const MOBILE_AUTO_HEIGHT = 500;

    private const THUMBNAIL_MAX_WIDTH = 600;

    public function saving(Category $category): void
    {
        try {
            $disk = Storage::disk('public');

            if ($this->isLocalUpload($category, 'banner_desktop')) {
                $this->convertSingle($category, $disk, 'banner_desktop', self::DESKTOP_MAX_WIDTH, 'desktop');
            }

            $explicitMobileUpload = $this->isLocalUpload($category, 'banner_mobile');
            if ($explicitMobileUpload) {
                $this->convertSingle($category, $disk, 'banner_mobile', self::MOBILE_MAX_WIDTH, 'mobile');
                $category->banner_mobile_auto_generated = false;
            }

            $mobileClearedThisSave = $category->isDirty('banner_mobile') && blank($category->banner_mobile);
            $desktopChangedAndMobileIsOursToManage = $category->isDirty('banner_desktop')
                && ($category->banner_mobile_auto_generated || blank($category->banner_mobile));

            if (! $explicitMobileUpload && ($mobileClearedThisSave || $desktopChangedAndMobileIsOursToManage)) {
                $this->generateAutoMobile($category, $disk);
            }

            if ($this->isLocalUpload($category, 'thumbnail')) {
                $this->convertSingle($category, $disk, 'thumbnail', self::THUMBNAIL_MAX_WIDTH, 'thumb');
            }
        } catch (\Throwable $e) {
            // A conversion failure must never block saving the category --
            // the admin still gets their original upload(s), just without
            // the generated WebP output.
            Log::error('Category image conversion failed.', [
                'category_id' => $category->id,
                'error' => $e->getMessage(),
            ]);
        }
    }

    private function isLocalUpload(Category $category, string $field): bool
    {
        return $category->isDirty($field)
            && filled($category->{$field})
            && ! Str::startsWith($category->{$field}, ['http://', 'https://']);
    }

    private function convertSingle(Category $category, $disk, string $field, int $maxWidth, string $tag): void
    {
        $originalPath = $category->{$field};

        if (! $disk->exists($originalPath)) {
            return;
        }

        $source = WebpImage::decode($disk->path($originalPath));
        if ($source->width() > $maxWidth) {
            $source->scaleDown(width: $maxWidth);
        }

        $directory = 'categories/generated';
        $disk->makeDirectory($directory);
        $path = "{$directory}/".Str::uuid()."-{$tag}.webp";
        $disk->put($path, WebpImage::encode($source));

        $category->{$field} = $path;
        $category->{"{$field}_width"} = $source->width();
        $category->{"{$field}_height"} = $source->height();
    }

    private function generateAutoMobile(Category $category, $disk): void
    {
        if (blank($category->banner_desktop) || ! $disk->exists($category->banner_desktop)) {
            $category->banner_mobile = null;
            $category->banner_mobile_width = null;
            $category->banner_mobile_height = null;
            $category->banner_mobile_auto_generated = false;

            return;
        }

        $source = WebpImage::decode($disk->path($category->banner_desktop));
        $source->cover(self::MOBILE_AUTO_WIDTH, self::MOBILE_AUTO_HEIGHT);

        $directory = 'categories/generated';
        $disk->makeDirectory($directory);
        $path = "{$directory}/".Str::uuid().'-mobile-auto.webp';
        $disk->put($path, WebpImage::encode($source));

        $category->banner_mobile = $path;
        $category->banner_mobile_width = self::MOBILE_AUTO_WIDTH;
        $category->banner_mobile_height = self::MOBILE_AUTO_HEIGHT;
        $category->banner_mobile_auto_generated = true;
    }
}
